const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const read = (rel) => fs.readFileSync(path.join(__dirname, "..", rel), "utf8");
const camera = read("screens/CameraScreen.js");
const grouping = read("screens/GroupingScreen.js");
const analysis = read("screens/AnalysisScreen.js");
const profile = read("screens/ProfileScreen.js");
const app = read("App.js");
const api = read("src/api.js");
const theme = read("src/theme.js");
const store = read("src/photoStore.js");
const paths = read("src/photoPaths.js");

assert.match(camera, /source: "camera"/);
assert.match(camera, /source: "library"/);
assert.match(camera, /cameraSetNumber\(shots\)/);
assert.match(camera, /groupId: null/);
assert.match(camera, /nextScreen\(next, "library"\)/);
assert.doesNotMatch(camera, /nextScreen\(next, "camera"\)/);
assert.match(camera, /navigate\("Photos"/);
assert.match(camera, /filter: "all"/);
assert.match(camera, /accessibilityLabel="Storage"/);
assert.match(camera, /accessibilityLabel="Analyze"/);
assert.match(camera, /accessibilityLabel="This session"/);
assert.match(camera, /accessibilityLabel="Upload"/);
assert.match(camera, /accessibilityLabel="Profile"/);
assert.match(camera, /albums-outline/);
assert.match(camera, /shotsInSet/);
assert.match(camera, /sessionCount/);
assert.match(camera, /filter: setNumber/);
assert.match(camera, /type: "single"/);
assert.match(camera, /removeFromSets/);
assert.doesNotMatch(camera, /circleSpacer/);
assert.match(camera, /person-outline/);
assert.match(camera, /This session/);
assert.match(camera, /cloud-upload-outline/);
assert.match(camera, /images-outline/);
assert.match(camera, /name="search"/);
assert.match(camera, /appendCaptured/);
assert.match(camera, /loadPersistedShots/);
assert.doesNotMatch(camera, /clearPersisted/);
assert.doesNotMatch(camera, /Practice sets/);
assert.doesNotMatch(camera, /ActionBar/);
assert.doesNotMatch(camera, /rememberShots\(\[\]\)/);

assert.match(grouping, /Create Set/);
assert.match(grouping, /Create Set \(\$\{selected\.size\}\)/);
assert.match(grouping, /Remove from set/);
assert.match(grouping, /Add to set/);
assert.match(grouping, /addToSetLabel/);
assert.match(grouping, /canAddToSet/);
assert.match(grouping, /accessibilityLabel="Add to set"/);
assert.match(grouping, /Delete/);
assert.match(grouping, /Select all/);
assert.match(grouping, /Delete all/);
assert.match(grouping, /ActionBar/);
assert.match(grouping, /clearPersisted/);
assert.match(grouping, /Back to camera/);
assert.match(grouping, />Analyze</);
assert.match(grouping, /visibleIndexes/);
assert.match(grouping, /SetFilterBar/);
assert.match(grouping, /includeUnassigned/);
assert.match(grouping, /cellSelected/);
assert.match(grouping, /gridWrap/);
assert.match(grouping, /width: window\.width/);
assert.match(grouping, /width: cellW, height: cellH/);
assert.match(grouping, /loadPersistedShots/);
assert.doesNotMatch(grouping, /cellClip/);
assert.doesNotMatch(grouping, /gridContent: \{ flexDirection: "row"/);
assert.match(grouping, /SetBadge/);
assert.match(grouping, /deletePersisted/);
assert.match(grouping, /assignedShots/);
assert.match(grouping, /canAnalyze\(shots\)/);
assert.match(grouping, /scope: \{ type: "storage" \}/);
assert.match(grouping, /storageFilter/);
assert.match(grouping, /route\.params\?\.filter/);

assert.match(analysis, /loadPersistedShots/);
assert.match(analysis, /sessionShots/);
assert.match(analysis, /No saved photos to check/);
assert.match(analysis, /SetFilterBar/);
assert.match(analysis, /overviewOpen/);
assert.match(analysis, /directionalLockEnabled/);
assert.match(analysis, /checklistClosed/);
assert.match(analysis, /scopedShots/);
assert.match(analysis, /useFocusEffect/);
assert.match(analysis, /analysisReady && !singlePhoto \? \(/);
assert.match(analysis, /canAddSingle/);
assert.match(analysis, /accessibilityLabel="Add to set"/);
assert.match(analysis, /addSingleToSet/);
assert.match(analysis, /assignSet/);
assert.match(analysis, /addToSetLabel/);
assert.match(analysis, /storedSets/);
assert.match(analysis, /New set/);
assert.match(analysis, /animationType="fade"/);
assert.match(analysis, /shotIds/);
assert.doesNotMatch(analysis, /showSet=\{filter === "all"\}/);
assert.match(analysis, /setBeside/);
assert.match(analysis, /includeUnassigned=\{false\}/);
assert.doesNotMatch(camera, /ActionBar/);
assert.doesNotMatch(camera, /ActionGroup/);
assert.match(grouping, /<ActionGroup full/);
assert.match(grouping, /ActionGroup full>\s*\r?\n\s*<Pressable[\s\S]*?Select all/);
assert.match(grouping, /toolGrow: \{ flex: 1 \}/);
assert.match(grouping, /styles\.actions/);
assert.doesNotMatch(grouping, /ActionGroup full style=\{\[styles\.actions/);
assert.match(analysis, /onPanResponderTerminationRequest: \(\) => false/);
assert.match(analysis, /navigate\("Photos"/);
assert.match(analysis, /HOLD_MS/);
assert.match(analysis, /onTouchStart/);
assert.match(analysis, /onHoldCenter/);
assert.match(analysis, /storageFilterFromShot/);
assert.match(analysis, /Problem/);
assert.match(analysis, /Solution/);
assert.match(analysis, /styles\.viewBlock/);
assert.match(analysis, /testID="viewBlock"/);
assert.doesNotMatch(analysis, /viewKicker/);
assert.doesNotMatch(analysis, />View</);
assert.match(analysis, /styles\.problemBlock/);
assert.match(analysis, /testID="problemBlock"/);
assert.match(analysis, /styles\.solutionBlock/);
assert.match(analysis, /testID="solutionBlock"/);
assert.match(analysis, /styles\.blockKicker/);
assert.match(analysis, /styles\.blockBody/);
assert.doesNotMatch(analysis, /issue_codes/);
assert.doesNotMatch(analysis, /explainLabel/);
assert.match(analysis, /itemKeys/);
assert.doesNotMatch(analysis, /No defect code/);
assert.doesNotMatch(analysis, /styles\.issues/);
assert.doesNotMatch(analysis, /key=\{photo\.image_id/);
assert.doesNotMatch(analysis, /PhotoGrid/);
assert.doesNotMatch(analysis, /setGrid/);
assert.doesNotMatch(analysis, /onOpenGrid/);
assert.doesNotMatch(analysis, /Tap a photo to open it in the roller/);

const filterBar = read("src/SetFilterBar.js");
assert.match(filterBar, /Modal/);
assert.match(filterBar, /ScrollView/);
assert.match(filterBar, /filterItems/);
assert.match(filterBar, /filterLabel/);
assert.match(filterBar, /rgba\(23, 50, 77, 0.18\)/);
assert.doesNotMatch(filterBar, /flexWrap: "wrap"/);
assert.match(analysis, /Analysis in Progress/);
assert.match(analysis, /size="small"/);
assert.match(analysis, /analysisReady/);
assert.match(analysis, /displayPhotos/);
assert.match(analysis, /resultFromCache/);
assert.doesNotMatch(analysis, /Checking this set/);
assert.match(camera, /navigate\("Analysis"/);
assert.match(camera, /function openSessionAnalysis/);
assert.match(camera, /function openStorageAnalysis/);
assert.doesNotMatch(analysis.slice(analysis.indexOf("function PhotoCarousel")), /SetBadge/);

assert.match(app, /GroupingScreen/);
assert.match(app, /ProfileScreen/);
assert.match(app, /name="Photos"/);
assert.match(app, /name="Profile"/);
assert.match(profile, /Sign in/);
assert.match(profile, /Sign out/);
assert.match(profile, /signIn\(/);
assert.match(profile, /Sync now/);
assert.match(app, /title: "Storage"/);

assert.match(paths, /device-shots/);
assert.match(store, /copyAsync/);
assert.match(store, /loadPersistedShots/);
assert.match(store, /persistAnalyzeCache/);
assert.match(store, /loadAnalyzeCache/);
assert.match(api, /payloadGroupId\(shot\)/);
assert.match(api, /ImageManipulator/);
assert.match(api, /UPLOAD_MAX_SIDE = 960/);
assert.match(api, /Promise\.all/);
assert.match(api, /partitionShots/);
assert.match(api, /keepResponse/);
assert.match(api, /status === 503/);
assert.match(api, /HEALTH_MS = 4000/);
assert.match(api, /AbortController/);
assert.match(store, /clearAnalyzeCache/);
assert.match(store, /clearCameraSession/);
assert.match(store, /forgetShots/);
assert.match(theme, /setColors:/);

console.log("screen contracts ok");
